### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Yonet** [Yonet/angular2-d3#1]
- [x] Syntax highlight
- [x] Change the graph to something simpler
- [x] Angular 1 example app in repo
- [x] Angular 2 example app in repo
- [x] Write the render function, show how to steal from d3 website
